{
 "title": "Cluster overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(cluster_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node table",
   "type": "table",
   "gridPos": { "h": 18, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "cluster_node_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Convergance state",
   "type": "stat",
   "description": "Whether the cluster state has converged. \n\nIt is normal for the cluster state to be diverged briefly as gossip events propagate. It is not normal for the cluster state to be diverged for a long period of time.\n\nThis will show one of the following: \n\n* Converged: Nodes are aware of all other nodes, with the correct states. \n* Not converged: A subset of nodes aren't aware of their peers, or don't have an updated view of peer states.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "suffix:nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp((\r\n  sum(stddev by (state) (cluster_node_peers) != 0) or \r\n  (sum(abs(sum without (state) (cluster_node_peers)) - scalar(count(cluster_node_info)) != 0))\r\n), 1, 1)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}