{
 "title": "Cluster node",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(cluster_node_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(cluster_node_lamport_time{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster_node_update_observers{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster_node_gossip_health_score{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster_node_gossip_proto_version{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gossip ops/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(cluster_node_gossip_received_events_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Known peers",
   "type": "stat",
   "description": "Known peers to the node (including the local node)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "suffix:peers" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_node_peers{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "suffix:nodes" } },
   "targets": [
    {
     "expr": "cluster_node_peers{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Gossip transport", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Transport bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(cluster_transport_rx_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "rx"
    },
    {
     "expr": "-1 * rate(cluster_transport_tx_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Packet write success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ( \r\n    rate(cluster_transport_tx_packets_failed_total{instance=\"$instance\"}[$__rate_interval]) / \r\n    rate(cluster_transport_tx_packets_total{instance=\"$instance\"}[$__rate_interval])\r\n)",
     "legendFormat": "Tx success %"
    },
    {
     "expr": "1 - ( \r\n    rate(cluster_transport_rx_packets_failed_total{instance=\"$instance\"}[$__rate_interval]) / \r\n    rate(cluster_transport_rx_packets_total{instance=\"$instance\"}[$__rate_interval])\r\n)",
     "legendFormat": "Rx success %"
    }
   ]
  },
  {
   "title": "Pending packet queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pkts" } },
   "targets": [
    {
     "expr": "cluster_transport_tx_packet_queue_length{instance=\"$instance\"}",
     "legendFormat": "tx queue"
    },
    {
     "expr": "cluster_transport_rx_packet_queue_length{instance=\"$instance\"}",
     "legendFormat": "rx queue"
    }
   ]
  },
  {
   "title": "Stream bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(cluster_transport_stream_rx_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "rx"
    },
    {
     "expr": "-1 * rate(cluster_transport_stream_tx_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Stream write success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ( \r\n    rate(cluster_transport_stream_tx_packets_failed_total{instance=\"$instance\"}[$__rate_interval]) / \r\n    rate(cluster_transport_stream_tx_packets_total{instance=\"$instance\"}[$__rate_interval])\r\n)",
     "legendFormat": "Tx success %"
    },
    {
     "expr": "1 - ( \r\n    rate(cluster_transport_stream_rx_packets_failed_total{instance=\"$instance\"}[$__rate_interval]) / \r\n    rate(cluster_transport_stream_rx_packets_total{instance=\"$instance\"}[$__rate_interval])\r\n)",
     "legendFormat": "Rx success %"
    }
   ]
  },
  {
   "title": "Open transport streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cluster_transport_streams{instance=\"$instance\"}",
     "legendFormat": "Open streams"
    }
   ]
  }
 ]
}